ALTER TABLE "Exam"
ADD COLUMN "maxViolations" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN "calculatorEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isTestExam" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ExamAttempt"
ADD COLUMN "maxViolations" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN "calculatorEnabled" BOOLEAN NOT NULL DEFAULT false;
